export const UNAUTHORIZED_CLOSE_CODE = 4001;
export const SESSION_REVOKED_CLOSE_CODE = 4002;
export const ORGANIZATION_FORBIDDEN_CLOSE_CODE = 4003;

export const HEARTBEAT_INTERVAL_MS = 30_000;
export const HEARTBEAT_TIMEOUT_MS = 75_000;
